// Typed access to the FLORES+ excerpt (generated by scripts/build_flores_sample.py;
// do not edit flores.json by hand). CC BY-SA 4.0 — the Languages view shows the
// attribution next to the table.
import raw from "./flores.json";

export interface FloresLanguage {
  code: string;
  name: string;
  native: string;
  script: string;
  sentences: string[];
}

export const FLORES = raw as {
  source: string;
  license: string;
  url: string;
  languages: FloresLanguage[];
};
